name: GitHub Metrics

on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: omirfarhan
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Dhaka

          # Plugins
          plugin_commits: yes
          plugin_commits_sections: all
          plugin_commits_history: 1y
          plugin_isocalendar: yes
          plugin_followup: yes
          plugin_stargazers: yes
          plugin_lines: yes
          plugin_people: yes
          plugin_reactions: yes
          plugin_achievements: yes
          plugin_traffic: yes
